In [3]:
import pandas as pd
import numpy as np
import joblib

In [5]:
df = pd.read_csv('project4_waste_generation.csv')
df

,Week_Start_Date,Neighborhood,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
0,2020-01-06,Bambili,4432,432,8.3,0,0,1,1,2736.7
1,2020-01-13,Bambili,4403,428,8.4,0,0,1,1,2407.3
2,2020-01-20,Bambili,4360,427,8.3,0,0,1,1,2346.0
3,2020-01-27,Bambili,4373,433,8.4,0,0,1,1,2831.3
4,2020-02-03,Bambili,4352,426,7.7,0,0,1,2,2688.3
...,...,...,...,...,...,...,...,...,...,...
9995,2024-09-09,Abakwa,1350,15,7.0,1,0,1,9,952.9
9996,2024-09-16,Abakwa,1330,21,7.1,1,0,1,9,954.8
9997,2024-09-23,Abakwa,1355,22,7.0,1,0,1,9,1308.1
9998,2024-09-30,Abakwa,1318,17,6.7,1,0,1,9,913.2
9999,2024-10-07,Abakwa,1357,18,7.0,1,0,1,10,1022.5

In [9]:
df.head()

,Week_Start_Date,Neighborhood,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
0,2020-01-06,Bambili,4432,432,8.3,0,0,1,1,2736.7
1,2020-01-13,Bambili,4403,428,8.4,0,0,1,1,2407.3
2,2020-01-20,Bambili,4360,427,8.3,0,0,1,1,2346.0
3,2020-01-27,Bambili,4373,433,8.4,0,0,1,1,2831.3
4,2020-02-03,Bambili,4352,426,7.7,0,0,1,2,2688.3

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Week_Start_Date                10000 non-null  object
 1   Neighborhood                   10000 non-null  object
 2   Population_Density_per_km2     10000 non-null  int64
 3   Number_of_Businesses           10000 non-null  int64
 4   Avg_Household_Size             10000 non-null  float64
 5   Market_Present                 10000 non-null  int64
 6   Industrial_Zone                10000 non-null  int64
 7   Collection_Frequency_per_Week  10000 non-null  int64
 8   Month                          10000 non-null  int64
 9   Weekly_Waste_Weight_kg         10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB

In [11]:
df.describe()

,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2477.740600,282.957100,6.007350,0.600000,0.280000,1.960000,6.483300,2103.634690
std,1222.465775,174.487167,1.475059,0.489922,0.449021,0.773602,3.447537,690.010899
min,198.000000,8.000000,2.900000,0.000000,0.000000,1.000000,1.000000,736.300000
25%,1444.000000,123.000000,4.700000,0.000000,0.000000,1.000000,4.000000,1581.725000
50%,2567.000000,298.000000,6.100000,1.000000,0.000000,2.000000,7.000000,2072.700000
75%,3515.000000,426.000000,7.200000,1.000000,1.000000,3.000000,10.000000,2582.125000
max,4502.000000,569.000000,9.100000,1.000000,1.000000,3.000000,12.000000,4603.700000

In [12]:
df.isnull().sum()

Week_Start_Date                  0
Neighborhood                     0
Population_Density_per_km2       0
Number_of_Businesses             0
Avg_Household_Size               0
Market_Present                   0
Industrial_Zone                  0
Collection_Frequency_per_Week    0
Month                            0
Weekly_Waste_Weight_kg           0
dtype: int64

In [14]:
X = df.drop('Week_Start_Date',axis = 1)
y = df['Weekly_Waste_Weight_kg']

In [15]:
X.head()

,Neighborhood,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month,Weekly_Waste_Weight_kg
0,Bambili,4432,432,8.3,0,0,1,1,2736.7
1,Bambili,4403,428,8.4,0,0,1,1,2407.3
2,Bambili,4360,427,8.3,0,0,1,1,2346.0
3,Bambili,4373,433,8.4,0,0,1,1,2831.3
4,Bambili,4352,426,7.7,0,0,1,2,2688.3

In [16]:
X = X.iloc[:,1:-1]
X

,Population_Density_per_km2,Number_of_Businesses,Avg_Household_Size,Market_Present,Industrial_Zone,Collection_Frequency_per_Week,Month
0,4432,432,8.3,0,0,1,1
1,4403,428,8.4,0,0,1,1
2,4360,427,8.3,0,0,1,1
3,4373,433,8.4,0,0,1,1
4,4352,426,7.7,0,0,1,2
...,...,...,...,...,...,...,...
9995,1350,15,7.0,1,0,1,9
9996,1330,21,7.1,1,0,1,9
9997,1355,22,7.0,1,0,1,9
9998,1318,17,6.7,1,0,1,9
9999,1357,18,7.0,1,0,1,10

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(f'training set shape: {X_train.shape}')
print(f'test set shape: {X_test.shape}')

training set shape: (8000, 7)
test set shape: (2000, 7)

In [22]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

LinearRegression()

In [29]:
model.fit(X_train_scaled, y_train)
print('model training complete')

model training complete

In [31]:
prediction = model.predict(X_test_scaled)
prediction

array([2156.01686061, 1844.89401726, 1865.86445449, ..., 2990.74370781,
       2168.9705777 , 1944.44311578])

In [33]:
model.intercept_

2105.3625625

In [35]:
model.coef_

array([577.73105388, 330.93175904,  44.63271351,  94.96270791,
       150.31727117,  -0.67083303, -45.97169966])

In [41]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_test, prediction)
r2 = r2_score(y_test, prediction)

In [43]:
print(f'mean squared error: {mse:.2f}')
print(f'r2 score: {r2:.2f}')

mean squared error: 83668.90
r2 score: 0.83